In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import env
from MACROS import *

In [2]:
m = env.Mendikot(cards_per_player=4)
m.reset()
m.game_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [3]:
for i in range(0,10, 4):
    print(i)

0
4
8


In [4]:
SUITS = ['S', 'H', 'C', 'D']
CARDS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
CARD_IDX = np.arange(len(CARDS)*len(SUITS)).reshape(len(CARDS), len(SUITS))

print(CARD_IDX[CARDS.index('5'),SUITS.index('S')])

12


Get Card Data from game_matrix

In [5]:
# PRINT THE game_matrix
mendikot = env.Mendikot()

macro_list = [
    "CARD_FOR_PLAYING",
    "CARD_IN_HAND_AGENT",
    "CARD_IN_HAND_OPPNT_1",
    "CARD_IN_HAND_TEAM",
    "CARD_IN_HAND_OPPNT_2",
    "CARD_AVAILABLE",
    "CARD_CURR_TRICK_AGENT",
    "CARD_CURR_TRICK_OPPNT_1",
    "CARD_CURR_TRICK_TEAM",
    "CARD_CURR_TRICK_OPPNT_2",
    "CARD_PREV_TRICK_AGENT",
    "CARD_PREV_TRICK_OPPNT_1",
    "CARD_PREV_TRICK_TEAM",
    "CARD_PREV_TRICK_OPPNT_2",
    "CARD_TRUMP"
]

card = '9'
suit = 'S'

card_index = CARD_IDX[CARDS.index(card), SUITS.index(suit)]
print(f"Card: {card} {suit}")
print(f"Card Index : {card_index}")

print("\n--------------------------\n")
for item in macro_list:
    print(f"{item} : {mendikot.game_matrix[card_index,macro_list.index(item)]}")


Card: 9 S
Card Index : 28

--------------------------

CARD_FOR_PLAYING : 0.0
CARD_IN_HAND_AGENT : 0.0
CARD_IN_HAND_OPPNT_1 : 0.0
CARD_IN_HAND_TEAM : 0.0
CARD_IN_HAND_OPPNT_2 : 0.0
CARD_AVAILABLE : 0.0
CARD_CURR_TRICK_AGENT : 0.0
CARD_CURR_TRICK_OPPNT_1 : 0.0
CARD_CURR_TRICK_TEAM : 0.0
CARD_CURR_TRICK_OPPNT_2 : 0.0
CARD_PREV_TRICK_AGENT : 0.0
CARD_PREV_TRICK_OPPNT_1 : 0.0
CARD_PREV_TRICK_TEAM : 0.0
CARD_PREV_TRICK_OPPNT_2 : 0.0
CARD_TRUMP : 0.0


In [16]:
m = env.Mendikot(cards_per_player=4)
m.reset()
m.game_matrix
print(m.get_cards_in_play())


id1 = m.get_cards_in_hand(AGENT)
print(id1)
id2 = m.get_cards_in_hand(OPPONENT_1)
print(id2)
id3 = m.get_cards_in_hand(OPPONENT_2)
print(id3)
id4 = m.get_cards_in_hand(TEAMMATE)
print(id4)


card = np.random.choice(id1)
m.step(action=card, player_type=AGENT)
card = np.random.choice(id2)
m.step(action=card, player_type=OPPONENT_1)
card = np.random.choice(id3)
m.step(action=card, player_type=OPPONENT_2)
card = np.random.choice(id4)
m.step(action=card, player_type=TEAMMATE)

m.update_game()


id = m.get_cards_in_trick()
print(id)

[32 33 34 35 40 41 42 43 44 45 46 47 48 49 50 51]
[35 42 46 51]
[32 41 43 48]
[33 34 45 50]
[40 44 47 49]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[]


In [7]:
mendikot.get_cards_in_play()

array([], dtype=int64)

THIS FILE SHALL BE USED FOR TESTING