In [199]:
%load_ext autoreload
%autoreload 2
import numpy as np
import env
from MACROS import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [200]:
m = env.Mendikot(cards_per_player=4)
m.reset()
m.game_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [201]:
for i in range(0,10, 4):
    print(i)

0
4
8


In [202]:
SUITS = ['S', 'H', 'C', 'D']
CARDS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
CARD_IDX = np.arange(len(CARDS)*len(SUITS)).reshape(len(CARDS), len(SUITS))

print(CARD_IDX[CARDS.index('5'),SUITS.index('S')])

12


Get Card Data from game_matrix

In [203]:
# PRINT THE game_matrix
mendikot = env.Mendikot()

macro_list = [
    "CARD_FOR_PLAYING",
    "CARD_IN_HAND_AGENT",
    "CARD_IN_HAND_OPPNT_1",
    "CARD_IN_HAND_TEAM",
    "CARD_IN_HAND_OPPNT_2",
    "CARD_AVAILABLE",
    "CARD_CURR_TRICK_AGENT",
    "CARD_CURR_TRICK_OPPNT_1",
    "CARD_CURR_TRICK_TEAM",
    "CARD_CURR_TRICK_OPPNT_2",
    "CARD_PREV_TRICK_AGENT",
    "CARD_PREV_TRICK_OPPNT_1",
    "CARD_PREV_TRICK_TEAM",
    "CARD_PREV_TRICK_OPPNT_2",
    "CARD_TRUMP"
]

card = '9'
suit = 'S'

card_index = CARD_IDX[CARDS.index(card), SUITS.index(suit)]
print(f"Card: {card} {suit}")
print(f"Card Index : {card_index}")

print("\n--------------------------\n")
for item in macro_list:
    print(f"{item} : {mendikot.game_matrix[card_index,macro_list.index(item)]}")


Card: 9 S
Card Index : 28

--------------------------

CARD_FOR_PLAYING : 0.0
CARD_IN_HAND_AGENT : 0.0
CARD_IN_HAND_OPPNT_1 : 0.0
CARD_IN_HAND_TEAM : 0.0
CARD_IN_HAND_OPPNT_2 : 0.0
CARD_AVAILABLE : 0.0
CARD_CURR_TRICK_AGENT : 0.0
CARD_CURR_TRICK_OPPNT_1 : 0.0
CARD_CURR_TRICK_TEAM : 0.0
CARD_CURR_TRICK_OPPNT_2 : 0.0
CARD_PREV_TRICK_AGENT : 0.0
CARD_PREV_TRICK_OPPNT_1 : 0.0
CARD_PREV_TRICK_TEAM : 0.0
CARD_PREV_TRICK_OPPNT_2 : 0.0
CARD_TRUMP : 0.0


In [205]:
m = env.Mendikot(cards_per_player=5)
m.reset()
# print(m.get_cards_in_play())

# Card in Hand -each player
id1 = m.get_cards_in_hand(AGENT)
print(id1)
id2 = m.get_cards_in_hand(OPPONENT_1)
print(id2)
id3 = m.get_cards_in_hand(OPPONENT_2)
print(id3)
id4 = m.get_cards_in_hand(TEAMMATE)
print(id4)

# Play 4 steps in order
card = np.random.choice(id1)
m.get_render_str(card)
m.step(action=card, player_type=AGENT)

card = np.random.choice(id2)
m.get_render_str(card)
m.step(action=card, player_type=OPPONENT_1)

card = np.random.choice(id3)
m.get_render_str(card)
m.step(action=card, player_type=OPPONENT_2)

card = np.random.choice(id4)
m.get_render_str(card)
m.step(action=card, player_type=TEAMMATE)

m.evaluate_trick()
# m.update_game()

# prev_trick = m.get_cards_in_prev_trick(player=TEAMMATE)
# print(prev_trick)

# id = m.get_cards_in_trick()
# print(id)

[33 34 42 46 47]
[32 40 43 45 51]
[35 37 38 44 49]
[36 39 41 48 50]


AssertionError: Please call get_available_cards() first

In [210]:
m = env.Mendikot(cards_per_player=13)
m.reset()

print("Starting Game")
for p in range(AGENT, OPPONENT_2+1):
    cards = m.get_available_cards(p)
    render_str = m.get_render_str(cards_list=cards)
    print(f"{PLAYER_RENDER[p]:}\t{render_str}")
print(f"TRUMP\t{SUITS_RENDER[m.trump_suit]}")

c = np.random.choice(m.get_available_cards(AGENT))
print(m.get_render_str(c))
m.step(c, AGENT)

c = np.random.choice(m.get_available_cards(OPPONENT_1))
print(m.get_render_str(c))
m.step(c, OPPONENT_1)

c = np.random.choice(m.get_available_cards(TEAMMATE))
print(m.get_render_str(c))
m.step(c, TEAMMATE)

c = np.random.choice(m.get_available_cards(OPPONENT_2))
print(m.get_render_str(c))
m.step(c, OPPONENT_2)

winner = m.evaluate_trick()
print(f"Winner is {PLAYER_RENDER[winner]}")

Starting Game
AGENT	2♣ 2♦ 5♥ 6♣ 6♦ 7♥ 8♥ 9♦ Q♠ Q♥ K♣ A♠ A♣ 
OPPNT1	2♠ 3♥ 4♠ 4♥ 5♣ 5♦ 6♠ 8♠ 8♣ 8♦ 9♥ T♥ J♣ 
TEAM	2♥ 6♥ 7♣ 7♦ T♠ J♠ Q♣ Q♦ K♠ K♥ K♦ A♥ A♦ 
OPPNT2	3♠ 3♣ 3♦ 4♣ 4♦ 5♠ 7♠ 9♠ 9♣ T♣ T♦ J♥ J♦ 
TRUMP	♥
5♥
3♥
K♥
J♥
WINNER! K♥
Winner is TEAM


THIS FILE SHALL BE USED FOR TESTING